"""initial schema

Revision ID: b21d3caaaff3
Revises: 
Create Date: 2026-05-29 12:56:02.127070

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b21d3caaaff3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clubs',
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('logo_url', sa.String(length=2048), nullable=True),
    sa.Column('department', sa.String(length=128), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_clubs_department', 'clubs', ['department'], unique=False)
    op.create_table('users',
    sa.Column('google_id', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('avatar_url', sa.String(length=2048), nullable=True),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('department', sa.String(length=128), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('google_id')
    )
    op.create_index('ix_users_email', 'users', ['email'], unique=False)
    op.create_index('ix_users_google_id', 'users', ['google_id'], unique=False)
    op.create_index('ix_users_role', 'users', ['role'], unique=False)
    op.create_table('audit_logs',
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=128), nullable=False),
    sa.Column('resource_type', sa.String(length=64), nullable=True),
    sa.Column('resource_id', sa.String(length=128), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_logs_resource', 'audit_logs', ['resource_type', 'resource_id'], unique=False)
    op.create_index('ix_audit_logs_user_id', 'audit_logs', ['user_id'], unique=False)
    op.create_table('events',
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('slug', sa.String(length=300), nullable=False),
    sa.Column('banner_url', sa.String(length=2048), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('agenda', sa.Text(), nullable=True),
    sa.Column('rules', sa.Text(), nullable=True),
    sa.Column('venue', sa.String(length=512), nullable=True),
    sa.Column('start_datetime', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_datetime', sa.DateTime(timezone=True), nullable=True),
    sa.Column('registration_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('registration_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('category', sa.String(length=64), nullable=True),
    sa.Column('event_type', sa.String(length=16), nullable=False),
    sa.Column('external_event_url', sa.String(length=2048), nullable=True),
    sa.Column('organizer_club_id', sa.UUID(), nullable=False),
    sa.Column('faculty_advisor_id', sa.UUID(), nullable=True),
    sa.Column('visibility', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('max_participants', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['faculty_advisor_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organizer_club_id'], ['clubs.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug'),
    sa.UniqueConstraint('slug', name='uq_events_slug')
    )
    op.create_index('ix_events_faculty_advisor_id', 'events', ['faculty_advisor_id'], unique=False)
    op.create_index('ix_events_organizer_club_id', 'events', ['organizer_club_id'], unique=False)
    op.create_index('ix_events_start_datetime', 'events', ['start_datetime'], unique=False)
    op.create_index('ix_events_status', 'events', ['status'], unique=False)
    op.create_table('notifications',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_notifications_is_read', 'notifications', ['is_read'], unique=False)
    op.create_index('ix_notifications_user_id', 'notifications', ['user_id'], unique=False)
    op.create_table('announcements',
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('sent_by', sa.UUID(), nullable=False),
    sa.Column('target_audience', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('channels', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sent_by'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_announcements_event_id', 'announcements', ['event_id'], unique=False)
    op.create_index('ix_announcements_sent_by', 'announcements', ['sent_by'], unique=False)
    op.create_table('certificate_templates',
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('certificate_type', sa.String(length=16), nullable=False),
    sa.Column('template_file_url', sa.String(length=2048), nullable=False),
    sa.Column('placeholders', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_certificate_templates_event_id', 'certificate_templates', ['event_id'], unique=False)
    op.create_index('ix_certificate_templates_type', 'certificate_templates', ['certificate_type'], unique=False)
    op.create_table('checkpoints',
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_checkpoints_event_id', 'checkpoints', ['event_id'], unique=False)
    op.create_table('event_budgets',
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('total_budget', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', name='uq_event_budgets_event')
    )
    op.create_index('ix_event_budgets_event_id', 'event_budgets', ['event_id'], unique=False)
    op.create_table('event_organizers',
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('permissions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'user_id', name='uq_event_organizers')
    )
    op.create_index('ix_event_organizers_event_id', 'event_organizers', ['event_id'], unique=False)
    op.create_index('ix_event_organizers_user_id', 'event_organizers', ['user_id'], unique=False)
    op.create_table('expenses',
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('bill_url', sa.String(length=2048), nullable=True),
    sa.Column('uploaded_by', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_expenses_event_id', 'expenses', ['event_id'], unique=False)
    op.create_index('ix_expenses_status', 'expenses', ['status'], unique=False)
    op.create_index('ix_expenses_uploaded_by', 'expenses', ['uploaded_by'], unique=False)
    op.create_table('faculty_approvals',
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('faculty_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['faculty_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_faculty_approvals_event_id', 'faculty_approvals', ['event_id'], unique=False)
    op.create_index('ix_faculty_approvals_faculty_id', 'faculty_approvals', ['faculty_id'], unique=False)
    op.create_table('feedback_forms',
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('closes_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_feedback_forms_event_id', 'feedback_forms', ['event_id'], unique=False)
    op.create_table('nps_scores',
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('respondent_id', sa.UUID(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['respondent_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_nps_scores_event_id', 'nps_scores', ['event_id'], unique=False)
    op.create_index('ix_nps_scores_respondent_id', 'nps_scores', ['respondent_id'], unique=False)
    op.create_table('sponsors',
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('logo_url', sa.String(length=2048), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('tier', sa.String(length=32), nullable=True),
    sa.Column('contact_person', sa.String(length=256), nullable=True),
    sa.Column('contact_email', sa.String(length=320), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sponsors_event_id', 'sponsors', ['event_id'], unique=False)
    op.create_table('teams',
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('lead_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('max_size', sa.Integer(), nullable=False),
    sa.Column('min_size', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lead_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_teams_event_id', 'teams', ['event_id'], unique=False)
    op.create_index('ix_teams_lead_id', 'teams', ['lead_id'], unique=False)
    op.create_index('ix_teams_status', 'teams', ['status'], unique=False)
    op.create_table('volunteer_positions',
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('slots', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_volunteer_positions_event_id', 'volunteer_positions', ['event_id'], unique=False)
    op.create_table('budget_categories',
    sa.Column('budget_id', sa.UUID(), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('allocated_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['budget_id'], ['event_budgets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_budget_categories_budget_id', 'budget_categories', ['budget_id'], unique=False)
    op.create_table('certificates',
    sa.Column('template_id', sa.UUID(), nullable=False),
    sa.Column('recipient_id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('certificate_type', sa.String(length=16), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('unique_code', sa.String(length=64), nullable=False),
    sa.Column('pdf_url', sa.String(length=2048), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['recipient_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['template_id'], ['certificate_templates.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('unique_code'),
    sa.UniqueConstraint('unique_code', name='uq_certificate_code')
    )
    op.create_index('ix_certificates_event_id', 'certificates', ['event_id'], unique=False)
    op.create_index('ix_certificates_recipient_id', 'certificates', ['recipient_id'], unique=False)
    op.create_index('ix_certificates_template_id', 'certificates', ['template_id'], unique=False)
    op.create_index('ix_certificates_unique_code', 'certificates', ['unique_code'], unique=False)
    op.create_table('feedback_questions',
    sa.Column('form_id', sa.UUID(), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('question_type', sa.String(length=24), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['form_id'], ['feedback_forms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_feedback_questions_form_id', 'feedback_questions', ['form_id'], unique=False)
    op.create_table('feedback_responses',
    sa.Column('form_id', sa.UUID(), nullable=False),
    sa.Column('respondent_id', sa.UUID(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['form_id'], ['feedback_forms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['respondent_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_feedback_responses_form_id', 'feedback_responses', ['form_id'], unique=False)
    op.create_index('ix_feedback_responses_respondent_id', 'feedback_responses', ['respondent_id'], unique=False)
    op.create_table('registrations',
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('team_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('qr_token', sa.String(length=1024), nullable=True),
    sa.Column('registered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'user_id', name='uq_registration_event_user'),
    sa.UniqueConstraint('qr_token'),
    sa.UniqueConstraint('qr_token', name='uq_registration_qr_token')
    )
    op.create_index('ix_registrations_event_id', 'registrations', ['event_id'], unique=False)
    op.create_index('ix_registrations_status', 'registrations', ['status'], unique=False)
    op.create_index('ix_registrations_team_id', 'registrations', ['team_id'], unique=False)
    op.create_index('ix_registrations_user_id', 'registrations', ['user_id'], unique=False)
    op.create_table('team_invitations',
    sa.Column('team_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('token', sa.String(length=256), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token'),
    sa.UniqueConstraint('token', name='uq_team_invitation_token')
    )
    op.create_index('ix_team_invitations_email', 'team_invitations', ['email'], unique=False)
    op.create_index('ix_team_invitations_team_id', 'team_invitations', ['team_id'], unique=False)
    op.create_table('team_members',
    sa.Column('team_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_id', 'user_id', name='uq_team_members')
    )
    op.create_index('ix_team_members_team_id', 'team_members', ['team_id'], unique=False)
    op.create_index('ix_team_members_user_id', 'team_members', ['user_id'], unique=False)
    op.create_table('volunteer_applications',
    sa.Column('position_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('assigned_at', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['position_id'], ['volunteer_positions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_volunteer_applications_position_id', 'volunteer_applications', ['position_id'], unique=False)
    op.create_index('ix_volunteer_applications_user_id', 'volunteer_applications', ['user_id'], unique=False)
    op.create_table('attendance_records',
    sa.Column('registration_id', sa.UUID(), nullable=False),
    sa.Column('checkpoint_id', sa.UUID(), nullable=False),
    sa.Column('scanned_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('scanned_by', sa.UUID(), nullable=False),
    sa.Column('is_duplicate', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['checkpoint_id'], ['checkpoints.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['registration_id'], ['registrations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scanned_by'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_attendance_checkpoint_id', 'attendance_records', ['checkpoint_id'], unique=False)
    op.create_index('ix_attendance_registration_id', 'attendance_records', ['registration_id'], unique=False)
    op.create_index('ix_attendance_scanned_by', 'attendance_records', ['scanned_by'], unique=False)
    op.create_table('feedback_answers',
    sa.Column('response_id', sa.UUID(), nullable=False),
    sa.Column('question_id', sa.UUID(), nullable=False),
    sa.Column('answer_value', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['feedback_questions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['response_id'], ['feedback_responses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_feedback_answers_question_id', 'feedback_answers', ['question_id'], unique=False)
    op.create_index('ix_feedback_answers_response_id', 'feedback_answers', ['response_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_feedback_answers_response_id', table_name='feedback_answers')
    op.drop_index('ix_feedback_answers_question_id', table_name='feedback_answers')
    op.drop_table('feedback_answers')
    op.drop_index('ix_attendance_scanned_by', table_name='attendance_records')
    op.drop_index('ix_attendance_registration_id', table_name='attendance_records')
    op.drop_index('ix_attendance_checkpoint_id', table_name='attendance_records')
    op.drop_table('attendance_records')
    op.drop_index('ix_volunteer_applications_user_id', table_name='volunteer_applications')
    op.drop_index('ix_volunteer_applications_position_id', table_name='volunteer_applications')
    op.drop_table('volunteer_applications')
    op.drop_index('ix_team_members_user_id', table_name='team_members')
    op.drop_index('ix_team_members_team_id', table_name='team_members')
    op.drop_table('team_members')
    op.drop_index('ix_team_invitations_team_id', table_name='team_invitations')
    op.drop_index('ix_team_invitations_email', table_name='team_invitations')
    op.drop_table('team_invitations')
    op.drop_index('ix_registrations_user_id', table_name='registrations')
    op.drop_index('ix_registrations_team_id', table_name='registrations')
    op.drop_index('ix_registrations_status', table_name='registrations')
    op.drop_index('ix_registrations_event_id', table_name='registrations')
    op.drop_table('registrations')
    op.drop_index('ix_feedback_responses_respondent_id', table_name='feedback_responses')
    op.drop_index('ix_feedback_responses_form_id', table_name='feedback_responses')
    op.drop_table('feedback_responses')
    op.drop_index('ix_feedback_questions_form_id', table_name='feedback_questions')
    op.drop_table('feedback_questions')
    op.drop_index('ix_certificates_unique_code', table_name='certificates')
    op.drop_index('ix_certificates_template_id', table_name='certificates')
    op.drop_index('ix_certificates_recipient_id', table_name='certificates')
    op.drop_index('ix_certificates_event_id', table_name='certificates')
    op.drop_table('certificates')
    op.drop_index('ix_budget_categories_budget_id', table_name='budget_categories')
    op.drop_table('budget_categories')
    op.drop_index('ix_volunteer_positions_event_id', table_name='volunteer_positions')
    op.drop_table('volunteer_positions')
    op.drop_index('ix_teams_status', table_name='teams')
    op.drop_index('ix_teams_lead_id', table_name='teams')
    op.drop_index('ix_teams_event_id', table_name='teams')
    op.drop_table('teams')
    op.drop_index('ix_sponsors_event_id', table_name='sponsors')
    op.drop_table('sponsors')
    op.drop_index('ix_nps_scores_respondent_id', table_name='nps_scores')
    op.drop_index('ix_nps_scores_event_id', table_name='nps_scores')
    op.drop_table('nps_scores')
    op.drop_index('ix_feedback_forms_event_id', table_name='feedback_forms')
    op.drop_table('feedback_forms')
    op.drop_index('ix_faculty_approvals_faculty_id', table_name='faculty_approvals')
    op.drop_index('ix_faculty_approvals_event_id', table_name='faculty_approvals')
    op.drop_table('faculty_approvals')
    op.drop_index('ix_expenses_uploaded_by', table_name='expenses')
    op.drop_index('ix_expenses_status', table_name='expenses')
    op.drop_index('ix_expenses_event_id', table_name='expenses')
    op.drop_table('expenses')
    op.drop_index('ix_event_organizers_user_id', table_name='event_organizers')
    op.drop_index('ix_event_organizers_event_id', table_name='event_organizers')
    op.drop_table('event_organizers')
    op.drop_index('ix_event_budgets_event_id', table_name='event_budgets')
    op.drop_table('event_budgets')
    op.drop_index('ix_checkpoints_event_id', table_name='checkpoints')
    op.drop_table('checkpoints')
    op.drop_index('ix_certificate_templates_type', table_name='certificate_templates')
    op.drop_index('ix_certificate_templates_event_id', table_name='certificate_templates')
    op.drop_table('certificate_templates')
    op.drop_index('ix_announcements_sent_by', table_name='announcements')
    op.drop_index('ix_announcements_event_id', table_name='announcements')
    op.drop_table('announcements')
    op.drop_index('ix_notifications_user_id', table_name='notifications')
    op.drop_index('ix_notifications_is_read', table_name='notifications')
    op.drop_table('notifications')
    op.drop_index('ix_events_status', table_name='events')
    op.drop_index('ix_events_start_datetime', table_name='events')
    op.drop_index('ix_events_organizer_club_id', table_name='events')
    op.drop_index('ix_events_faculty_advisor_id', table_name='events')
    op.drop_table('events')
    op.drop_index('ix_audit_logs_user_id', table_name='audit_logs')
    op.drop_index('ix_audit_logs_resource', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index('ix_users_role', table_name='users')
    op.drop_index('ix_users_google_id', table_name='users')
    op.drop_index('ix_users_email', table_name='users')
    op.drop_table('users')
    op.drop_index('ix_clubs_department', table_name='clubs')
    op.drop_table('clubs')
    # ### end Alembic commands ###
